name: Deploy App Monitoring

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "SPACE_KEY=${{ secrets.ARIZE_SPACE_KEY }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.ARIZE_API_KEY }}" >> $GITHUB_ENV
      - name: Set variable
        run: |   
          echo "MY_VAR=value" >> $GITHUB_ENV

      - name: Run Application
        run : gunicorn -w 4 -b 0.0.0.0:5000 app_monitoring:app &
          

#      - name: Run Application
#        run: python app_monitoring.py
